securityConfig:
  ciphersuite: blowfish/ECB/PKCS5Padding
  provider: SunJCE
  hmac: HMacSHA1
  keyStoreType: JCEKS
  keyStoreName: securityStore.jceks
  keyStorePassword: P4s5w0rd
  keyName: symkey
  keyPassword: P4s5w0rd
  signatureAlgorithm: SHA512withRSA
  signatureAlgProvider: SunRsaSign
  signatureKeyName: asymkey
  signatureKeyPassword: P4s5w0rd
  redisServer: 192.168.56.101
  redisPassword:


vmsTpm:
  host: 192.168.56.101
  port: 9999
  ciphersuite: aes/ECB/PKCS5Padding
  keySize: 256
  provider: SunJCE
  runningPrograms:
    - java
    - ps
  attestationHashes:
    - ac8ceaf262d81bf742a4539c69f7798e1263d7c4914586620da3e685597b363a # Sha256 of redis-server bin

gosTpm:
  host: locahost
  port: 8888
  ciphersuite: aes/ECB/PKCS5Padding
  keySize: 256
  provider: SunJCE